### ISSUE TITLE
KW2.0 编辑器 & Viewer

### ISSUE THREAD

**Issue by leopoldchen** [tatfook/KWPM#1]
### 背景

因调整技术架构，故借此机会重写KeepWork编辑器，重新设计交互，以提高KeepWork的整体使用体验。

### 目标

重写KeepWork编辑器，重新设计UIUX。

### 指标

- [ ] 提供优秀的MOD解决方案，极大地降低mod开发效率（mod团队缩减为1-2人）
- [ ] 优化界面交互，让初级用户使用起来也顺手（关于编辑器难用的反馈比例降低80%）
- [ ] 功能完整，支持绝大部分旧版本已包含的功能（参考产品功能清单）
